services:
  web:
    build: .
    volumes:
      - /srv/static/:/static/
    ports:
      - "9393:8000"
    env_file:
      - ./.env
    depends_on:
      - db

  db:
    image: postgres:16-alpine
    restart: unless-stopped
    volumes:
      - ./db/:/var/lib/postgresql/data/
    env_file:
      - ./.env

