# Generated by Django 5.0.7 on 2024-07-16 19:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="opportunity",
            options={},
        ),
        migrations.RenameField(
            model_name="opportunity",
            old_name="content",
            new_name="description",
        ),
        migrations.RemoveField(
            model_name="opportunity",
            name="applicants",
        ),
        migrations.RemoveField(
            model_name="opportunity",
            name="author",
        ),
        migrations.RemoveField(
            model_name="opportunity",
            name="created_at",
        ),
        migrations.RemoveField(
            model_name="opportunity",
            name="updated_at",
        ),
        migrations.AddField(
            model_name="opportunity",
            name="contact",
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name="opportunity",
            name="is_closed",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="opportunity",
            name="type",
            field=models.CharField(
                choices=[
                    ("Internship", "Internship"),
                    ("Full-time", "Full-time"),
                    ("Part-time", "Part-time"),
                    ("Contract", "Contract"),
                ],
                default="Internship",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="opportunity",
            name="company",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="opportunity",
            name="location",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="opportunity",
            name="posted_on",
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="opportunity",
            name="stipend",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
        migrations.AlterField(
            model_name="opportunity",
            name="title",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="user",
            name="interests",
            field=models.CharField(
                blank=True,
                help_text="Comma-separated list of interests",
                max_length=255,
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="skills",
            field=models.CharField(
                blank=True, help_text="Comma-separated list of skills", max_length=255
            ),
        ),
        migrations.DeleteModel(
            name="Internship",
        ),
    ]
