# Generated by Django 5.0.7 on 2024-07-18 17:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0002_alter_opportunity_options_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Scholarship",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField()),
                ("deadline", models.DateTimeField()),
                ("amount", models.DecimalField(decimal_places=2, max_digits=10)),
                ("contact", models.EmailField(blank=True, max_length=254)),
                ("posted_on", models.DateField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-deadline"],
            },
        ),
        migrations.AddField(
            model_name="user",
            name="applied_opportunities",
            field=models.ManyToManyField(
                blank=True, related_name="applicants", to="app.opportunity"
            ),
        ),
    ]
