# Generated by Django 5.0.7 on 2024-07-18 17:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0003_scholarship_user_applied_opportunities"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="opportunity",
            options={"verbose_name_plural": "Opportunities"},
        ),
        migrations.AlterField(
            model_name="opportunity",
            name="apply_by",
            field=models.DateField(blank=True),
        ),
    ]
