# Generated by Django 5.0.7 on 2024-07-18 18:01

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0004_alter_opportunity_options_alter_opportunity_apply_by"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="email",
        ),
    ]
