# Generated by Django 5.0.7 on 2024-07-18 19:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0005_remove_user_email"),
    ]

    operations = [
        migrations.AlterField(
            model_name="opportunity",
            name="apply_by",
            field=models.DateField(blank=True, null=True),
        ),
    ]
