# Generated by Django 5.0.7 on 2024-07-18 19:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0006_alter_opportunity_apply_by"),
    ]

    operations = [
        migrations.AlterField(
            model_name="opportunity",
            name="type",
            field=models.CharField(
                choices=[
                    ("Internship", "Internship"),
                    ("Full-time", "Full-time"),
                    ("Part-time", "Part-time"),
                    ("Contract", "Contract"),
                    ("Course", "Course"),
                    ("Workshop", "Workshop"),
                ],
                default="Internship",
                max_length=50,
            ),
        ),
    ]
